version: '3.2'

services:
  oracle-db:
    image: "gvenzl/oracle-xe:latest"
    ports:
      - 1521:1521
    environment:
      - ORACLE_PASSWORD=password
    volumes:
      - oracledb:/opt/oracle/oradata 

  app:
    build: 
      context: "python-with-oracle"
    volumes:
      - ./python-with-oracle:/app
    
volumes:
  oracledb: